### ISSUE TITLE
KeyError: '2019'

### ISSUE THREAD

**Issue by ryu-s** [ryu-s/electron-neon-test#2]
0a2d1af72d73e3a13a7629ef9d8026b35f9b0d88 で
```
yarn build
```
をすると以下のエラーを吐く
```
c:\Users\shinmura\Source\Repos\electron-neon-test>yarn build
yarn run v1.13.0
$ electron-build-env neon build --release
neon info forcing rebuild for new build settings
neon info running cargo
   Compiling semver-parser v0.7.0
   Compiling cfg-if v0.1.10
   Compiling smallvec v1.4.2
   Compiling cslice v0.2.0
   Compiling winapi v0.3.9
   Compiling neon-sys v0.5.1
   Compiling semver v0.9.0
error: failed to run custom build command for `neon-sys v0.5.1`

Caused by:
  process didn't exit successfully: `c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\release\build\neon-sys-aaea9add19962b8e\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to run "node-gyp configure" for neon-sys!
 Out:
> @ configure-release c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\release\build\neon-sys-3297128150c14be1\out\native
> node-gyp configure --verbose


c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\release\build\neon-sys-3297128150c14be1\out\native>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\Nodist\npmv\4.0.5\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --verbose )  else (node "" configure --verbose )

 Err: gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files (x86)\\Nodist\\v-x64\\14.15.0\\node.exe',
gyp verb cli   'C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--verbose'
gyp verb cli ]
gyp info using node-gyp@3.4.0
gyp info using node@14.15.0 | win32 | x64
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\shinmura\.windows-build-tools\python27\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\shinmura\.windows-build-tools\python27\python.exe C:\Users\shinmura\.windows-build-tools\python27\python.exe
gyp verb check python version `C:\Users\shinmura\.windows-build-tools\python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.15\r\n"
gyp verb get node dir compiling against --target node version: 10.1.5
gyp verb command install [ '10.1.5' ]
gyp verb install input version string "10.1.5"
gyp verb install installing version: 10.1.5
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.1.5
gyp verb build dir attempting to create "build" dir: c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\release\build\neon-sys-3297128150c14be1\out\native\build
gyp verb build dir "build" dir needed to be created? null
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\release\build\neon-sys-3297128150c14be1\out\native\build\config.gypi
gyp verb config.gypi checking for gypi file: c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\release\build\neon-sys-3297128150c14be1\out\native\config.gypi
gyp verb common.gypi checking for gypi file: c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\release\build\neon-sys-3297128150c14be1\out\native\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\shinmura\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2019',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\Users\\shinmura\\Source\\Repos\\electron-neon-test\\native\\target\\release\\build\\neon-sys-3297128150c14be1\\out\\native\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\shinmura\\.node-gyp\\10.1.5\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\shinmura\\.node-gyp\\10.1.5',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=c:\\Users\\shinmura\\Source\\Repos\\electron-neon-test\\native\\target\\release\\build\\neon-sys-3297128150c14be1\\out\\native',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'c:\\Users\\shinmura\\Source\\Repos\\electron-neon-test\\native\\target\\release\\build\\neon-sys-3297128150c14be1\\out\\native\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1900, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2019'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files (x86)\\Nodist\\v-x64\\14.15.0\\node.exe" "C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
gyp ERR! cwd c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\release\build\neon-sys-3297128150c14be1\out\native
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.19042
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v-x64\\14.15.0\\node.exe" "C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\bin\\npm-cli.js" "run" "configure-release"
npm ERR! node v14.15.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @ configure-release: `node-gyp configure --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ configure-release script 'node-gyp configure --verbose'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure --verbose
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\release\build\neon-sys-3297128150c14be1\out\native\npm-debug.log
', C:\Users\shinmura\.cargo\registry\src\github.com-1ecc6299db9ec823\neon-sys-0.5.1\build.rs:159:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `neon-sys v0.5.1`

Caused by:
  process didn't exit successfully: `c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\release\build\neon-sys-aaea9add19962b8e\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to run "node-gyp configure" for neon-sys!
 Out:
> @ configure-release c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\x86_64-pc-windows-msvc\release\build\neon-sys-d978a0cb984fcd9a\out\native
> node-gyp configure --verbose


c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\x86_64-pc-windows-msvc\release\build\neon-sys-d978a0cb984fcd9a\out\native>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\Nodist\npmv\4.0.5\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --verbose )  else (node "" configure --verbose )

 Err: gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files (x86)\\Nodist\\v-x64\\14.15.0\\node.exe',
gyp verb cli   'C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--verbose'
gyp verb cli ]
gyp info using node-gyp@3.4.0
gyp info using node@14.15.0 | win32 | x64
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\shinmura\.windows-build-tools\python27\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\shinmura\.windows-build-tools\python27\python.exe C:\Users\shinmura\.windows-build-tools\python27\python.exe
gyp verb check python version `C:\Users\shinmura\.windows-build-tools\python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.15\r\n"
gyp verb get node dir compiling against --target node version: 10.1.5
gyp verb command install [ '10.1.5' ]
gyp verb install input version string "10.1.5"
gyp verb install installing version: 10.1.5
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.1.5
gyp verb build dir attempting to create "build" dir: c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\x86_64-pc-windows-msvc\release\build\neon-sys-d978a0cb984fcd9a\out\native\build
gyp verb build dir "build" dir needed to be created? c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\x86_64-pc-windows-msvc\release\build\neon-sys-d978a0cb984fcd9a\out\native\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\x86_64-pc-windows-msvc\release\build\neon-sys-d978a0cb984fcd9a\out\native\build\config.gypi
gyp verb config.gypi checking for gypi file: c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\x86_64-pc-windows-msvc\release\build\neon-sys-d978a0cb984fcd9a\out\native\config.gypi
gyp verb common.gypi checking for gypi file: c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\x86_64-pc-windows-msvc\release\build\neon-sys-d978a0cb984fcd9a\out\native\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\shinmura\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2019',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\Users\\shinmura\\Source\\Repos\\electron-neon-test\\native\\target\\x86_64-pc-windows-msvc\\release\\build\\neon-sys-d978a0cb984fcd9a\\out\\native\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\shinmura\\.node-gyp\\10.1.5\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\shinmura\\.node-gyp\\10.1.5',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=c:\\Users\\shinmura\\Source\\Repos\\electron-neon-test\\native\\target\\x86_64-pc-windows-msvc\\release\\build\\neon-sys-d978a0cb984fcd9a\\out\\native',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'c:\\Users\\shinmura\\Source\\Repos\\electron-neon-test\\native\\target\\x86_64-pc-windows-msvc\\release\\build\\neon-sys-d978a0cb984fcd9a\\out\\native\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1900, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2019'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files (x86)\\Nodist\\v-x64\\14.15.0\\node.exe" "C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
gyp ERR! cwd c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\x86_64-pc-windows-msvc\release\build\neon-sys-d978a0cb984fcd9a\out\native
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.19042
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v-x64\\14.15.0\\node.exe" "C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\bin\\npm-cli.js" "run" "configure-release"
npm ERR! node v14.15.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @ configure-release: `node-gyp configure --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ configure-release script 'node-gyp configure --verbose'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure --verbose
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\shinmura\Source\Repos\electron-neon-test\native\target\x86_64-pc-windows-msvc\release\build\neon-sys-d978a0cb984fcd9a\out\native\npm-debug.log
', C:\Users\shinmura\.cargo\registry\src\github.com-1ecc6299db9ec823\neon-sys-0.5.1\build.rs:159:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (c:\Users\shinmura\Source\Repos\electron-neon-test\node_modules\neon-cli\lib\target.js:98:27)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\shinmura\Source\Repos\electron-neon-test\node_modules\neon-cli\lib\target.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
electron-build-env error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ryu-s** [comment]
npmvをアップデートしたらできた
```
nodist npm match
```
バージョンが4.0.5から6.14.8になった
